/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

const fileMap = {
  
  "clients.baml": "// LLM requests go through LiteLLM proxy which handles:\n// - API key management (keys live in litellm/.env, not here)\n// - PII filtering via Presidio guardrails\n// - Observability via Langfuse\nclient<llm> LiteLlmProvider {\n  provider openai\n  options {\n    model \"gpt-4o-mini\"\n    api_key env.LITELLM_API_KEY\n    base_url \"http://localhost:4000/v1\"\n  }\n}\n\nclient<llm> LlmProvider {\n  provider fallback\n  options {\n    strategy [LiteLlmProvider]\n  }\n}\n",
  "generators.baml": "generator typescript {\n  output_type \"typescript\"\n  output_dir \"../\"\n  version \"0.220.0\"\n}\n",
  "main.baml": "class DimensionAssessment {\n  verdict \"PASS\" | \"WARN\" | \"FAIL\"\n  score int\n  explanation string\n}\n\nclass ProductAnalysis {\n  overallVerdict \"PASS\" | \"WARN\" | \"FAIL\"\n  descriptionQuality DimensionAssessment\n  categoryRelevance DimensionAssessment\n  priceAssessment DimensionAssessment\n  summary string\n}\n\nfunction AnalyzeProduct(\n  productName: string,\n  productDescription: string,\n  categoryName: string,\n  price: string\n) -> ProductAnalysis {\n  client LlmProvider\n  prompt #\"\n    You are a product quality analyst. Evaluate the following product across three dimensions.\n\n    Product Name: {{ productName }}\n    Product Description: {{ productDescription }}\n    Category: {{ categoryName }}\n    Price: {{ price }}\n\n    Evaluate each dimension and assign a verdict (PASS, WARN, or FAIL) with a score from 1 to 10 and a brief explanation:\n\n    1. Description Quality: Assess whether the description is accurate and complete relative to the product name. A good description clearly explains what the product is and its key features.\n\n    2. Category Relevance: Assess whether the assigned category is the most appropriate classification for this product. Consider whether a more specific or accurate category exists.\n\n    3. Price Assessment: Based on your training knowledge, estimate whether the price is normal, suspicious, or clearly wrong for this type of product in its category.\n\n    Also provide an overall verdict and a one-sentence summary suitable for a sidebar badge.\n\n    {{ ctx.output_format }}\n  \"#\n}\n",
}
export const getBamlFiles = () => {
    return fileMap;
}